---
apiVersion: v1
kind: Namespace
metadata:
  name: repro

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: repro
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
        - name: data
          hostPath:
            path: $DATA_PATH
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80
          volumeMounts:
            - name: data
              mountPath: /data
